repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: 'v2.1.0'
    hooks:
      - id: shell-fmt
        args:
          - -i
          - '2'
